language: python
python:
  - "3.4"
script: python3 travis_test.py
notifications:
  webhooks:
    urls:
      https://webhooks.gitter.im/e/a3ef7eb1b5c60d7451dd

    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

